### PR TITLE
(Fixed)[PXN-4214] - fix text style in installment header

### PR DESCRIPTION
**Pull request by matheusctMeli**
(Fixed)[PXN-4214] - fix text style in installment header

## What have changed?
fixed text style in installment header

[PXN-4214]: https://mercadolibre.atlassian.net/browse/PXN-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

new 
image

old
image

### CODE REVIEW

**Comment by mvarani** [comment]
Change looks good! Can we get before/after prints? :)

**Comment by matheusctMeli** [comment]
> Change looks good! Can we get before/after prints? :)

done

**Comment by lucschmidt** [comment]
Is there a case where the text will be displayed and does not need to have the UIColor.Andes.graySolid040 background?
Does this backgorund correspond to one selected parcel?
What if we have more parcels? It's possible?

**Review by lucschmidt — APPROVED** [review]

**Review by mvarani — APPROVED** [review]
LGTM!

**Pull request merged**
